name: Run Node script with repo secrets

on:
  workflow_dispatch:   # lets you manually trigger it from GitHub Actions tab

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run script (secrets injected)
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          # if you add a repo variable or secret for channel id:
          TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
        run: node ./script.js
